import json

entrada = {[
	{"nome": "Arad",
	"heuristica": 366,
	"arestas": [{"proximo": "Sibiu",
				"custo": 140},
				{"proximo": "Zerind",
				"custo": 75}]},

	{"nome": "Bucharest",
	"heuristica": 0,
	"arestas": ""},

	{"nome": "Craiova",
	"heuristica": 160,
	"arestas": [{"proximo": "Doberta",
				"custo": 120},
				{"proximo": "Pitesti",
				"custo": 138,
				"proximo": "Rimnicu Vilcea",
				"custo": 145}]},

	{"nome": "Doberta",
	"heuristica": 242,
	"arestas": [{"proximo": "Craiova",
				"custo": 120},
				{"proximo": "Melhadia",
				"custo": 75}]},

	{"nome": "Eforie",
	"heuristica": 161,
	"arestas": [{"proximo": "Hirsova",
				"custo": 86}]},

	{"nome": "Fagaras",
	"heuristica": 176},
	{"nome": "Giurgiu",
	"heuristica": 77},
	{"nome": "Hirsova",
	"heuristica": 151},
	{"nome": "Iasi",
	"heuristica": 226},
	{"nome": "Lugoj",
	"heuristica": 244},
	{"nome": "Melhadia",
	"heuristica": 241},
	{"nome": "Neamt",
	"heuristica": 234},
	{"nome": "Oradea",
	"heuristica": 380},
	{"nome": "Pitesti",
	"heuristica": 10},
	{"nome": "Rimnicu Vilcea",
	"heuristica": 193},
	{"nome": "Sibiu",
	"heuristica": 253},
	{"nome": "Timisoara",
	"heuristica": 329},
	{"nome": "Urziceni",
	"heuristica": 80},
	{"nome": "Vaslui",
	"heuristica": 199},
	{"nome": "Zerind",
	"heuristica": 374},
	
]}