import json

entrada = {[
	{"nome": "Arad",
	"custo": 366},
	{"nome": "Bucharest",
	"custo": 0},
	{"nome": "Craiova",
	"custo": 160},
	{"nome": "Doberta",
	"custo": 242},
	{"nome": "Eforie",
	"custo": 161},
	{"nome": "Fagaras",
	"custo": 176},
	{"nome": "Giurgiu",
	"custo": 77},
	{"nome": "Hirsova",
	"custo": 151},
	{"nome": "Iasi",
	"custo": 226},
	{"nome": "Lugoj",
	"custo": 244},
	{"nome": "Melhadia",
	"custo": 241},
	{"nome": "Neamt",
	"custo": 234},
	{"nome": "Oradea",
	"custo": 380},
	{"nome": "Pitesti",
	"custo": 10},
	{"nome": "Rimnicu Vilcea",
	"custo": 193},
	{"nome": "Sibiu",
	"custo": 253},
	{"nome": "Timisoara",
	"custo": 329},
	{"nome": "Urziceni",
	"custo": 80},
	{"nome": "Vaslui",
	"custo": 199},
	{"nome": "Zerind",
	"custo": 374},
	
]}